[package]
name = "comprehensive-resource-example"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "comprehensive-resource-example"
path = "src/main.rs"

[dependencies]
mcp-derive = { path = "../../crates/mcp-derive" }
mcp-server = { path = "../../crates/mcp-server" }
mcp-protocol = { path = "../../crates/mcp-protocol-2025-06-18", package = "mcp-protocol-2025-06-18" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
uuid = { version = "1.0", features = ["v4"] }
chrono = { workspace = true }