[package]
name = "spec-compliant-server"
version = "0.1.0"
edition.workspace = true

[dependencies]
mcp-derive = { workspace = true }
mcp-server = { workspace = true }
mcp-protocol = { workspace = true }
mcp-protocol-2025-06-18 = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }