[package]
name = "zero-config-getting-started"
version = "0.1.0"
edition.workspace = true

[dependencies]
mcp-server.workspace = true
mcp-derive.workspace = true
mcp-protocol.workspace = true

tokio.workspace = true
serde_json.workspace = true
tracing-subscriber.workspace = true
async-trait.workspace = true

[features]
default = ["mcp-server/http"]