[package]
name = "lambda-mcp-server"
version = "0.1.0"
edition.workspace = true
description = "AWS Lambda serverless MCP server using mcp-framework components"
license = "MIT"

[[bin]]
name = "lambda-mcp-server"
path = "src/main.rs"

[dependencies]
# Lambda runtime with streaming support
lambda_http.workspace = true
lambda_runtime.workspace = true

# AWS SDK for DynamoDB, SNS, SQS integration
aws-config.workspace = true
aws-sdk-dynamodb.workspace = true
aws-sdk-sns.workspace = true
aws-sdk-sqs.workspace = true

# Our MCP framework
mcp-server = { workspace = true }
http-mcp-server = { workspace = true }
mcp-protocol = { workspace = true }
mcp-derive = { workspace = true }
mcp-json-rpc-server = { workspace = true }
async-trait = { workspace = true }

# HTTP and JSON handling
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
# HTTP and Hyper support for streaming
http = { workspace = true }
hyper = { workspace = true }

# Date/time handling
chrono = { workspace = true }

# Async runtime
tokio = { workspace = true }
futures = { workspace = true }

# Error handling and logging
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# URL encoding for SSE parameters
urlencoding = { workspace = true }

[dev-dependencies]
tokio-test.workspace = true

[features]
default = ["lambda"]
lambda = []
local = []
